name: Release Workflow

on:
  workflow_dispatch:

jobs:
  release:
    name: Build and Sign
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build JAR
        run: mvn clean install -Dskiptests=true

      - name: Create container
        run: docker build -t jscott932/app-java-demo:latest .
          
      - name: Get Image Digest to Sign
        run: |
         IMAGE_SHA=$(docker inspect app-java-demo:1.0.0 | jq -r '.[].Id')
         IMAGE_NAME=app-java-demo
         SIGNING_TARGET="$IMAGE_NAME"@"$IMAGE_SHA"
         echo ARTIFACT="$SIGNING_TARGET" >> $GITHUB_ENV

      - name: Container sign
        uses: endorlabs/github-action/sign@v1.1.2
        with:
          namespace: "yolo"
          artifact_name: ${{ env.ARTIFACT }}

      - name: Run Java Tests
        run: |
          mvn test
          
      - name: Endor Labs Dependency Scan
        uses: endorlabs/github-action@v1.1.2
        with:
          namespace: ${{ github.event.inputs.tenant_name }}
          scan_summary_output_type: "table"
          pr: "false"
          enable_github_action_token: "true"
          scan_dependencies: "true"
          scan_secrets: "true"
          scan_git_logs: "true"

      - name: Run SAST
        run: python3 -m pip install semgrep && semgrep scan

      - name: Container verify
        uses: endorlabs/github-action/verify@v1.1.2
        with:
          namespace: "yolo"
          artifact_name: ${{ env.ARTIFACT }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push jscott932/app-java-demo:latest
