name: Release Workflow

on:
  workflow_dispatch:
  push: 
  
jobs:
  release:
    name: Build and Sign
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build JAR
        run: mvn clean install -Dskiptests=true

      - name: Create container
        run: docker build -t jscott932/app-java-demo:latest .

      - name: Get Image Digest to Sign
        run: |
         IMAGE_SHA=$(docker inspect jscott932/app-java-demo:latest | jq -r '.[].Id')
         IMAGE_NAME=jscott932/app-java-demo
         SIGNING_TARGET="$IMAGE_NAME"@"$IMAGE_SHA"
         echo ARTIFACT="$SIGNING_TARGET" >> $GITHUB_ENV

      - name: Container Sign
        uses: endorlabs/github-action/sign@main
        with:
          api: https://api.staging.endorlabs.com
          namespace: "demo"
          artifact_name: ${{ env.ARTIFACT }}

      - name: Endor Labs Scan
        run: |
          curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
          echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c;
            if [ $? -ne 0 ]; then 
            echo "Integrity check failed"; 
            exit 1;
          fi
          chmod +x ./endorctl
          ./endorctl scan --container=jscott932/app-java-demo:latest --dependencies --secrets --git-logs --tools --path=./ --enable-github-action-token=true -n demo -a https://api.staging.endorlabs.com

      - name: Get Image Digest to Verify
        run: |
         VERIFY_SHA=$(docker inspect jscott932/app-java-demo:latest | jq -r '.[].Id')
         VERIFY_IMAGE_NAME=jscott932/app-java-demo
         VERIFY_TARGET="$VERIFY_IMAGE_NAME"@"$VERIFY_SHA"
         echo VERIFY_ARTIFACT="$VERIFY_TARGET" >> $GITHUB_ENV
         
      - name: Container verify
        uses: endorlabs/github-action/verify@main
        with:
          namespace: "demo"
          api: https://api.staging.endorlabs.com
          artifact_name: ${{ env.VERIFY_ARTIFACT }}
          certificate_oidc_issuer: "https://token.actions.githubusercontent.com"
