
name: Run UIA manually

on:
  workflow_dispatch:
    inputs:
      api:
        description: "Enter the target Endor Labs API"
        required: true
        type: choice
        default: https://api.endorlabs.com
        options:
        - https://api.staging.endorlabs.com
        - https://api.endorlabs.com
      tenant_name:
        description: "Enter your Endor Labs namespace?"
        required: true
        type: string

jobs:
  release:
    name: Run UIA Manually
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Run UIA Manually
        run: |
          curl https://api.endorlabs.com/download/endorlabs/v1.6.575/binaries/endorctl_v1.6.575_macos_arm64 -o endorctl
          echo "16b5cb1a239c30a8da01abaeb0df0ed7f703ba89bd1dcb5ce5f070ef97c685eb  endorctl" | shasum -a 256 --check
          chmod +x ./endorctl
          NUMBER_OF_PROJECTS=$(endorctl api list --enable-github-action-token=true -n ${{ github.event.inputs.tenant_name }}  --api=${{ github.event.inputs.api }} -r Project --count | jq -r '.count_response.count')
          echo "The number of projects to update is $NUMBER_OF_PROJECTS"
          i=0  
          while [ $i -lt "$NUMBER_OF_PROJECTS" ]
          do
              echo "Processing project $i"
              UUID_TO_UPDATE=$(endorctl api list -r Project --enable-github-action-token=true -n ${{ github.event.inputs.tenant_name }}  --api=${{ github.event.inputs.api }} | jq -r ".list.objects[$i].uuid")
          
              if [ -z "$UUID_TO_UPDATE" ]; then
                  echo "No UUID found for index $i, skipping."
                  i=$((i+1))
                  continue
              fi
          
              echo "Updating project with UUID $UUID_TO_UPDATE"
              endorctl recommend dependency-upgrades --enable-github-action-token=true -n ${{ github.event.inputs.tenant_name }} --api=${{ github.event.inputs.api }} --security-only --use-cia --persist --project-uuid="$UUID_TO_UPDATE"
              i=$((i+1))
          done
